
-- MYSQL 中的 IN 和OUT, IN是传入，OUT 是传出，默认是IN
DELIMITER //
CREATE PROCEDURE USP_GETEMPLOYEENAME(IN ID INT, OUT NAME VARCHAR(20))
BEGIN
SELECT EMP_NAME INTO NAME FROM EMPLOYEE WHERE EMP_ID = ID;
END//
DELIMITER ;
CALL USP_GETEMPLOYEENAME(103, @NAME);
SELECT @NAME;


